#!/usr/bin/env python3
"""
Assemble per-scenario fragments (written by plot_results.py) into the GitHub
Pages index.html: intro + M1..M5 narrative arc + each scenario section, with
Mermaid rendered client-side and a light/dark responsive layout.

Usage: build_site.py --site site
"""
from __future__ import annotations

import argparse
import glob
from pathlib import Path

INTRO = """
<p>This page is the visual output of a network simulation. It models a
time-sensitive LAN where many devices keep their clocks synchronized to one
"grandmaster" using gPTP (the IEEE&nbsp;802.1AS standard), while also sending
data through shared switches. The question it explores: <strong>when the data
traffic gets heavy, does it disturb the clock synchronization?</strong></p>
<p>Each section below is one experiment. You do not need to be an engineer:
read the plain-language verdict, glance at the network diagram (which devices,
which links, which knobs were set), and the plots show what happened over the
60&nbsp;seconds of simulated time.</p>
"""

STORYLINE = """
<ul class="arc">
  <li><strong>M1 / M2</strong> - devices with deliberately mismatched clocks all
      converge and stay synced; error stays tiny (microseconds).</li>
  <li><strong>M3</strong> - sustained data congestion on a shared link degrades the
      sync of the one device on that link ~100x, while everyone else is untouched.</li>
  <li><strong>M4</strong> - the same congestion delivered as periodic bursts (that drain
      between cycles) does <em>not</em> disturb sync at all.</li>
  <li><strong>M5</strong> - making the switch buffer bigger does not reduce packet loss
      under sustained overload; it only adds delay.</li>
</ul>
<p class="takeaway"><strong>Takeaway:</strong> congestion hurts clock sync only when it is
<em>sustained</em> and shares a queue with the sync messages - not merely when it is heavy.</p>
"""

CSS = """
:root { color-scheme: light dark; --bg:#ffffff; --fg:#1a1a1a; --card:#f6f8fa;
        --border:#d0d7de; --muted:#57606a; --accent:#0969da; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#0d1117; --fg:#e6edf3; --card:#161b22; --border:#30363d;
          --muted:#8b949e; --accent:#4493f8; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg); line-height:1.55;
       font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width:1100px; margin:0 auto; padding:2rem 1.2rem 4rem; }
h1 { font-size:1.9rem; margin:.2rem 0 .6rem; }
h2 { margin-top:2.4rem; padding-top:1.2rem; border-top:2px solid var(--border); }
section { scroll-margin-top:1rem; }
.verdict { background:var(--card); border:1px solid var(--border); border-left:4px solid var(--accent);
           border-radius:8px; padding:.6rem 1rem; margin:1rem 0; }
.verdict p { margin:.5rem 0; }
.note { color:var(--muted); font-size:.92rem; }
.two-col { display:grid; grid-template-columns:minmax(280px,380px) 1fr; gap:1.5rem; align-items:start; }
@media (max-width:820px){ .two-col { grid-template-columns:1fr; } }
.diagram pre.mermaid { background:var(--card); border:1px solid var(--border); border-radius:8px; padding:.6rem; overflow-x:auto; }
table.levers { width:100%; border-collapse:collapse; margin-top:.8rem; font-size:.9rem; }
table.levers th { text-align:left; color:var(--muted); font-weight:600; padding:.25rem .6rem .25rem 0; vertical-align:top; white-space:nowrap; }
table.levers td { padding:.25rem 0; }
.plots figure { margin:0 0 1.2rem; }
.plots img { width:100%; height:auto; border:1px solid var(--border); border-radius:8px; background:#fff; }
.plots figcaption { color:var(--muted); font-size:.88rem; margin-top:.3rem; }
.arc { line-height:1.7; } .takeaway { background:var(--card); border-radius:8px; padding:.6rem 1rem; }
footer { margin-top:3rem; color:var(--muted); font-size:.85rem; border-top:1px solid var(--border); padding-top:1rem; }
a { color:var(--accent); }
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--site", required=True)
    args = ap.parse_args()
    site = Path(args.site)

    frags = sorted(glob.glob(str(site / "*.frag.html")))
    body = "\n".join(Path(f).read_text() for f in frags)

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>syncsim - gPTP + TSN simulation results</title>
<style>{CSS}</style>
</head>
<body>
<div class="wrap">
  <h1>gPTP + TSN network simulation - results</h1>
  {INTRO}
  <h2 style="border-top:none;margin-top:1.5rem">The story in five experiments</h2>
  {STORYLINE}
  {body}
  <footer>
    Auto-generated by CI from headless simulation runs -- OMNeT++/INET (the
    authoritative M1-M5 results) plus a parallel, non-destructive ns-3 POC
    track (NS3_MIGRATION_SURVEY.md / NS3_MIGRATION_POC_PLAN.md) reproducing
    the same scenarios on a different simulator. Deterministic and
    reproducible: every number here comes from the runs whose raw results are
    attached as CI artifacts. Source: <a href="https://github.com/yoavbendor/syncsim">yoavbendor/syncsim</a>.
  </footer>
</div>
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  const dark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
  mermaid.initialize({{ startOnLoad: true, theme: dark ? 'dark' : 'default' }});
</script>
</body>
</html>
"""
    (site / "index.html").write_text(html)
    print(f"[site] wrote {site}/index.html from {len(frags)} fragment(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
