#!/usr/bin/env python3
"""
Phase B: generate a NED network, an .ini lever fragment, and a Mermaid
diagram from one YAML topology model (configs/topology/*.yaml) -- so the
network structure, per-node clock drift, and gPTP master/slave roles have a
single source of truth instead of being hand-maintained in parallel in a
.ned file and duplicated across every scenario .ini.

Gate/port numbering (why link order in the YAML matters):
OMNeT++ NED "gate++" allocates each endpoint's port indices in the order its
module appears as a connection endpoint. This generator walks `links` in
the given order (parent listed first, i.e. closer to the grandmaster) and
counts, per node, how many times it has appeared as the parent side ("a")
vs the child side ("b"). A node's gPTP master ports are exactly the gate
indices where it appeared as "a" (facing a child) -- unlisted ports default
to slave, which covers the "b" appearance (facing the parent). This
reproduces the exact eth0/eth1/... numbering already verified in the
hand-written minimal.ned/nominal.ned (see their header comments).

Usage:
    gen_topology.py <topology.yaml> --out-ned FILE --out-ini FILE
    gen_topology.py <topology.yaml> --mermaid   # print Mermaid + levers only
"""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

NED_TYPES = {"TsnClock", "TsnSwitch", "TsnDevice"}


def load_model(yaml_path: Path) -> dict:
    model = yaml.safe_load(Path(yaml_path).read_text())
    names = [n["name"] for n in model["nodes"]]
    if len(names) != len(set(names)):
        raise ValueError(f"{yaml_path}: duplicate node names")
    for a, b in model["links"]:
        for n in (a, b):
            if n not in names:
                raise ValueError(f"{yaml_path}: link references unknown node {n!r}")
    return model


def _count_expr(node: dict) -> str:
    """NED-side size expression for a vector node: a param name or a literal."""
    if "count_param" in node:
        return node["count_param"]
    return str(node["count"])


def _is_vector(node: dict) -> bool:
    return "count" in node or "count_param" in node


def build_gates(model: dict) -> list[dict]:
    """Expand `links` into concrete per-node gate assignments, in NED order.

    Returns a list of edges: {a, a_gate, b, b_gate, a_is_vector_elem, b_is_vector_elem}.
    Vector links (switch -> vector-of-clients) expand into one edge per index.
    """
    nodes = {n["name"]: n for n in model["nodes"]}
    counter: dict[str, int] = {}

    def next_gate(name: str) -> int:
        g = counter.get(name, 0)
        counter[name] = g + 1
        return g

    edges = []
    for a, b in model["links"]:
        b_node = nodes[b]
        if _is_vector(b_node):
            count = b_node.get("count")
            expand_n = count if count is not None else None
            # count_param: the literal fan-out count must still be known to
            # emit one gate-consuming edge per index; require an explicit
            # `count` alongside count_param for that, else fall back to
            # `count_param`'s value carried in model["params"].
            if expand_n is None:
                expand_n = model.get("params", {}).get(b_node["count_param"])
            if expand_n is None:
                raise ValueError(
                    f"vector node {b!r} needs 'count' or a resolvable 'count_param'"
                )
            for i in range(expand_n):
                edges.append({
                    "a": a, "a_gate": next_gate(a),
                    "b": b, "b_gate": next_gate(b), "b_index": i,
                })
        else:
            edges.append({"a": a, "a_gate": next_gate(a), "b": b, "b_gate": next_gate(b)})
    return edges


def master_ports(model: dict, edges: list[dict]) -> dict[str, list[str]]:
    ports: dict[str, set[int]] = {}
    for e in edges:
        ports.setdefault(e["a"], set()).add(e["a_gate"])
    return {name: [f"eth{i}" for i in sorted(idxs)] for name, idxs in ports.items()}


# ---- .ned emission ---------------------------------------------------------

def _grid_pos(i: int, cols: int, dx: int = 220, dy: int = 140, x0: int = 150, y0: int = 80) -> tuple[int, int]:
    return x0 + (i % cols) * dx, y0 + (i // cols) * dy


def render_ned(model: dict, edges: list[dict]) -> str:
    net = model["network"]
    lines = [
        "//",
        f"// Generated by scripts/gen_topology.py from configs/topology/{net.lower()}.yaml.",
        "// Do not hand-edit -- edit the YAML model and regenerate.",
        "//",
        "import inet.networks.base.TsnNetworkBase;",
        "import inet.node.ethernet.EthernetLink;",
        "import inet.node.tsn.TsnClock;",
        "import inet.node.tsn.TsnDevice;",
        "import inet.node.tsn.TsnSwitch;",
        "",
        f"network {net} extends TsnNetworkBase",
        "{",
    ]
    params = model.get("params", {})
    if params:
        lines.append("    parameters:")
        for k, v in params.items():
            lines.append(f"        int {k} = default({v});")
    lines.append("    submodules:")
    for i, node in enumerate(model["nodes"]):
        x, y = _grid_pos(i, cols=4)
        size = f"[{_count_expr(node)}]" if _is_vector(node) else ""
        lines.append(f"        {node['name']}{size}: {node['type']} {{")
        lines.append(f'            @display("p={x},{y}");')
        lines.append("        }")
    lines.append("    connections:")
    seen_vector_group = set()
    for a, b in model["links"]:
        b_node = next(n for n in model["nodes"] if n["name"] == b)
        if _is_vector(b_node):
            if b in seen_vector_group:
                continue
            seen_vector_group.add(b)
            lines.append(f"        for i=0..{_count_expr(b_node)}-1 {{")
            lines.append(f"            {a}.ethg++ <--> EthernetLink <--> {b}[i].ethg++;")
            lines.append("        }")
        else:
            lines.append(f"        {a}.ethg++ <--> EthernetLink <--> {b}.ethg++;")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ---- .ini fragment emission -------------------------------------------------

def render_ini(model: dict, edges: list[dict]) -> str:
    net = model["network"]
    mports = master_ports(model, edges)
    lines = [
        "# Generated by scripts/gen_topology.py -- topology/clock/gPTP levers only.",
        "# Do not hand-edit -- edit the YAML model and regenerate.",
        "[General]",
        f"network = {net}",
        f"sim-time-limit = {model['sim_time_limit']}",
        "",
        "*.*.hasTimeSynchronization = true",
        "",
        "**.clock.oscillator.typename = \"ConstantDriftOscillator\"",
    ]
    for node in model["nodes"]:
        sel = f"*.{node['name']}[*]" if _is_vector(node) else f"*.{node['name']}"
        lines.append(f"{sel}.clock.oscillator.driftRate = {node['drift']}")
    lines.append("")
    lines.append("# --- gPTP roles: master ports declared; every unlisted port is a slave ---")
    for node in model["nodes"]:
        name = node["name"]
        if name in mports:
            ports = ", ".join(f'"{p}"' for p in mports[name])
            lines.append(f"*.{name}.gptp.masterPorts = [{ports}]")
    lines.append("")
    lines.append(f"*.*.eth[*].bitrate = {model['link_bitrate']}")
    lines.append("")
    lines.append("**.referenceClock = \"gm.clock\"")
    lines.append("**.clock.timeChanged.result-recording-modes = +vector")
    lines.append("**.vector-recording = true")
    return "\n".join(lines) + "\n"


# ---- Mermaid emission (shared with gen_mermaid.py) --------------------------

_ROLE_CLASS = {"gm": "gm", "switch": "switch", "client": "client"}


def build_mermaid(model: dict, senders: set[str] | None = None) -> tuple[str, dict]:
    senders = senders or set()

    def nid(n: str) -> str:
        return n.replace("[", "_").replace("]", "")

    def label(node: dict) -> str:
        parts = [node["name"] + ("[*]" if _is_vector(node) else "")]
        if node["role"] == "gm":
            parts = [f"{node['name']} ⏱ GM"]
        drift = node.get("drift")
        if drift and drift not in ("0ppm",):
            parts.append(f"drift {drift.replace('uniform(', '').replace(')', '').replace(', ', '..')}")
        if node["name"] in senders:
            parts.append("📤 sender")
        return "<br/>".join(parts)

    lines = ["graph TD"]
    for node in model["nodes"]:
        lines.append(f'  {nid(node["name"])}["{label(node)}"]:::{_ROLE_CLASS[node["role"]]}')
    for a, b in model["links"]:
        lines.append(f"  {nid(a)} --- {nid(b)}")
    lines += [
        "  classDef gm fill:#f6c343,stroke:#b8860b,color:#222,stroke-width:2px;",
        "  classDef switch fill:#4a90d9,stroke:#26537a,color:#fff;",
        "  classDef client fill:#5cb85c,stroke:#2f6f2f,color:#fff;",
    ]
    levers = {
        "network": model["network"],
        "link speed": model["link_bitrate"],
        "grandmaster": next(n["name"] for n in model["nodes"] if n["role"] == "gm"),
        "nodes": len(model["nodes"]),
    }
    return "\n".join(lines), levers


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("yaml_path", type=Path)
    ap.add_argument("--out-ned")
    ap.add_argument("--out-ini")
    ap.add_argument("--mermaid", action="store_true")
    args = ap.parse_args()

    model = load_model(args.yaml_path)
    edges = build_gates(model)

    if args.out_ned:
        Path(args.out_ned).write_text(render_ned(model, edges))
        print(f"[gen_topology] wrote {args.out_ned}")
    if args.out_ini:
        Path(args.out_ini).write_text(render_ini(model, edges))
        print(f"[gen_topology] wrote {args.out_ini}")
    if args.mermaid or not (args.out_ned or args.out_ini):
        mermaid, levers = build_mermaid(model)
        print(mermaid)
        print("\n-- levers --")
        for k, v in levers.items():
            print(f"{k}: {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
